version: "3.2"
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
  cache-proxy:
    volumes:
      - ./api/docker/varnish/conf:/etc/varnish:ro
  h2-proxy:
      # Don't use this proxy in prod
      build:
        context: ./h2-proxy
      depends_on:
        - client
        - admin
        - api
        - cache-proxy
      ports:
        - "443:443"
        - "444:444"
        - "8443:8443"
        - "8444:8444"
